config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'welcome/home', to: 'welcome#home'
  get 'welcome/about', to: 'welcome#about'
  get 'pages/about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, expect: [:destroy]
  resources :articles
  resources :users, except: [:new]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: { minimum: 5, maximun: 50 }
  validates :description, presence: true, length: { minimum: 10, maximun: 300 }
  validates :user_id, presence: true

end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base

belongs_to :article
belongs_to :category


end

app/models/category.rb
class Category < ActiveRecord::Base

has_many :article_categories
has_many :articles, through: :article_categories

validates :name, presence: true, length: {minimum: 3, maximum: 25}
validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  before_save {self.email = email.downcase}
  validates :username, presence: true, uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 20 }
            VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false },
            length: { minimum: 7, maximum: 30 },
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find (session[:user_id]) if session[:user_id]

  end



  def logged_in?

    !! current_user # converted to boolean

  end

def require_user
  if !logged_in?
    flash[:danger] = "You must be logged in to perform that action"
    redirect_to root_path
  end

end

  #this is the fucntion that you created to check if a user in admin user and worked... good job Litchfield
  def admin_user
    if  !current_user.admin
      flash[:danger] = 'Please note that only administrators can create categories'
    end

  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]

  before_action :require_same_user, only: [:edit, :update]


  def index
    @article = Article.paginate(page: params[:page], per_page: 3).order(id: :desc)

  end

  def new
    if current_user.nil?
      redirect_to articles_path
      flash[:danger] = 'Please signup to create articles'

    else
      @article = Article.new

    end
  end

  def edit
    #if current_user != @article.user
      #flash[:danger] = 'You can only edit or delete your own articles'
      #redirect_to articles_path
    #end

  end


  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = 'Article successfully created'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article successfully updated'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show; end

  def destroy
    @article.destroy
    flash[:danger] = 'Article successfully deleted'
    redirect_to articles_path
  end


  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    #whitelisting
    params.require(:article).permit(:title, :description, category_ids:[]).merge(user: current_user)
  end

  def require_same_user

    if current_user != @article.user && !current_user.admin?
      flash[:danger] = 'You can only manage your own profile'
      redirect_to articles_path
    end

  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:edit, :update, :show, :destroy]


  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 3).order(id: :desc)
  end

  def new

    if admin_user
      redirect_to categories_path
    else
      @categories = Category.new

    end

  end

  def create

    @categories = Category.new(category_params)
    if @categories.save
      flash[:success] = 'Category successfully created'
      redirect_to categories_path(@categories)

    else
      render 'new'
    end

  end

  def show

    @categories_articles = @categories.articles.paginate(page: params[:page], per_page: 1).order(id: :desc)

  end

  def edit

  end

  def update
    if @categories.update(category_params)
      flash[:success] = 'Category successfully created'
      redirect_to category_path(@categories)
    else
    render 'edit'
    end
  end

  def destroy
    @categories.destroy
    flash[:danger] = 'Category successfully deleted'
    redirect_to categories_path
  end

  private

  def set_category
    @categories = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (!logged_in? and current_user.admin?)
      flash[:danger] = 'Please note that only administrators can create categories'
      redirect_to categories_path

    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def home

    redirect_to articles_path if logged_in?

  end

  def about


  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to articles_path if logged_in?

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)

    else
      flash.now[:danger] = "Please ensure that your email and password are correct"
      render 'new'
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :destroy]

  before_action :require_user, only: [:edit]


  def index
    @users = User.paginate(page: params[:page], per_page: 3).order(id: :desc)

  end


  def new
    redirect_to articles_path if logged_in?
    @users = User.new
  end


  def create
    @users = User.new(user_params)
    if @users.save
      session[:user_id] = @users.id
      flash[:success] = 'Welcome to the alpha blog'
      redirect_to user_path(@users)
    else
      render 'users/new' # or you can say render 'new'
    end
  end

  def edit

  end

  def show
    @users = User.find(params[:id])

    @user_paginate = @users.articles.paginate(page: params[:page], per_page: 1)


  end

  def update
    if @users.update(user_params)
      flash[:success] = 'Profile successfully updated'
      redirect_to users_path
    else
      render 'users/new'
    end
  end

  def destroy
    @users.destroy
    flash[:danger] = 'User successfully deleted'
    redirect_to articles_path
  end
  private

  def set_user
    @users = User.find(params[:id])
  end


  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_user

    if current_user != @users && !current_user.admin?
      flash[:danger] = 'You can only manage your own profile'
      redirect_to root_path
    end

  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


def home


end

def about


end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/views/articles/_articles.html.erb
<center>
  <% if obj.count > 0  %>

      <% obj.each do |article| %>

          <div class="row">

            <div class="col-xs-8 col-xs-offset-2">

              <div class="well well-lg">

                <div class="article-title">

                  <%= link_to article.title, article_path(article) %>

                </div>

                <div class="article-body">

                  <%= truncate(article.description, length: 100) %><hr/>
                  <small>Created by: <%= article.user.username if article.user%></small>
                  <br/>
                  <small>Created date: <%= time_ago_in_words(article.created_at) %> ago</small>
                  <br/>
                  <small>Updated date: <%= time_ago_in_words(article.updated_at) %> ago</small>

                  <% if article.categories.any? %>
                      <p>Categories: <%=render article.categories %></p>

                <% end %>


                </div>
                <%	 if logged_in? && (current_user == article.user || current_user.admin) %>

                <div class="article-actions">

                  <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>

                  <%= link_to "Delete this article", article_path(article), method: :delete,

                              data: { confirm: "Are you sure you want to delete the article?"},

                              class: "btn btn-xs btn-danger" %>

                </div>
                <%	end  %>

              </div>

            </div>

          </div>

      <% end %>
      <br/>
      <% if logged_in?  %>

      <%= link_to 'Create new article', new_article_url,:style =>'font-size:20px' %>

      <% end %>

<% else %>
      <center>
        <% if logged_in?  %>

      <%= link_to 'Create new article', new_article_url,:style =>'font-size:20px' %>
        <P>You currently do not have any articles created</P>
      </center>
        <% end %>

<% end %>
</center>

app/views/articles/_form.html.erb
  <%= render 'layouts/errors', obj:@article %>
    <div class="well">
      <%= form_for @article do  |f| %>
        <p>

          <%= f.label :title %><br/>
          <%= f.text_field :title, :class =>'form-control', :style =>'width: 50%;', :autofocus=>'true', :placeholder=>'Title' %>
        </p>
        <p>
          <%= f.label :description %><br/>
          <%= f.text_area :description, :class =>'form-control', :style =>'width: 50%; height: 150px;', :placeholder=>'Description' %>
        </p>
          <div class="form-group">

            <div class="row">

              <div class="col-sm-offset-2 col-sm-8">

                <%=f.collection_check_boxes(:category_ids, Category.all, :id, :name, prompt: true) do |b| %>
                    <% b.check_box
                       b.label(class: "checkbox-inline input_checkbox") do
                         b.check_box(class: "checkbox") + b.text %>
                    <% end %>
                <% end %>


              </div>

            </div>

          </div>


          <p>
          <%= f.submit :class => 'btn btn-primary' %>
        </p>
      <% end %>

      <br/>
      <%= link_to 'Articles', articles_path %>
    </div>

app/views/articles/edit.html.erb
<center><h1>Edit existing article</h1>


  <%= render 'form' %>


</center>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
  <center>
    <%= @article.count %>
    <br/>
  <%=	 will_paginate @article %>
<%=	 render 'articles', obj: @article %>

  <%=	 will_paginate @article %>
</center>

app/views/articles/new.html.erb
<center><H1>Create New Article</H1>

  <%=	 @test %>

<%= render 'form' %>

</center>

app/views/articles/show.html.erb
<center><h1>Show Page</h1>
<hr style="width: 25%"/>
<h4>
  <%= @article.title %>
</h4>
<hr style="width: 50%"/>

<h4>
  <%= @article.description %>
</h4>

  <hr style="width: 75%"/>

<h4>
  <% if @article.categories.any? %>
    <p>Categories: <%=render @article.categories %></p>
  <%end %>

</h4>

  <hr style="width: 75%"/>
    <%= link_to 'Articles', articles_path, :class => 'text-success',:style =>'font-size:20px'%> <br/>
  <%	 if logged_in? && (current_user == @article.user || current_user.admin?) %>
    <%= link_to 'Edit this article', edit_article_path(@article),:class => 'text-primary',:style =>'font-size:20px' %>  <br/>
    <%= link_to 'Delete this article', article_path(@article),:class => 'text-danger',:style =>'font-size:20px',method: :delete, data: {confirm: 'Are you sure?'} %><br/>
  <%	 end %>
  <hr/>


</center>

app/views/categories/_category.html.erb
<span class="well-sm"><%=link_to category.name, category_path(category)%> &nbsp;</span>

app/views/categories/_form.html.erb
<center>
  <%= render 'layouts/errors', obj:@categories %>
  <div class="well">
    <%= form_for @categories do  |f| %>
        <p>
          <%= f.label :name %><br/>
          <%= f.text_field :name, :class =>'form-control', :style =>'width: 50%;', :autofocus=>'true', :placeholder=>'Enter Category Name' %>
        </p>
        <p>
          <%= f.submit :class => 'btn btn-primary' %>
        </p>
    <% end %>

    <br/>
    <%= link_to 'Categories', categories_path %>
  </div>
</center>

app/views/categories/edit.html.erb
<H1 class="text-center">Edit category</H1>

  <%= render 'form' %>

app/views/categories/index.html.erb
<center>
  <% if @categories.count > 0  %>
      <h1>Categories</h1>
      <%=	 will_paginate @categories %>



      <% @categories.each do |category| %>



          <div class="row">

            <div class="col-xs-8 col-xs-offset-2">

              <div class="well well-lg">
                <p> <%if category.articles %>
                      <%= category.articles.count %>

                  <% end %> Articles</p>

                <div class="article-title">

                  <%= link_to category.name, category_path(category) %>

                </div>
                <%	 if logged_in? && (current_user.admin) %>

              <%= link_to "Edit this category", edit_category_path(category), class: "btn btn-xs btn-success" %>


                <% end %>
            </div>
          </div>
        </div>




<% end %>
      <%=	 will_paginate @categories %>

      <% else %>

  <p>There are no categories that are created as of yet</p>


  <% end %>
</center>

app/views/categories/new.html.erb
    <H1 class="text-center">Create new category</H1>

    <%= render 'form' %>

app/views/categories/show.html.erb
  <center>
<hr style="width: 25%"/>
  <h4>
   <h3>Category: <%= @categories.name %></h3>
  </h4>
  <hr style="width: 50%"/>
    <%=	 will_paginate @categories_articles %>


    <%= render 'articles/articles', obj: @categories_articles %>

    <%=	 will_paginate @categories_articles %>

</center>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>

    <div class="row">

      <div class="col-xs-8 col-xs-offset-2">

        <div class="panel panel-danger">

          <div class="panel-heading">

            <h2 class="panel-title">

              <%= pluralize(obj.errors.count, "error") %>

              prohibited this article from being saved:

            </h2>

            <div class="panel-body">

              <ul>

                <% obj.errors.full_messages.each do |msg| %>

                    <li><%= msg %></li>

                <% end %>

              </ul>

            </div>

          </div>

        </div>

      </div>

    </div>

<% end %>

app/views/layouts/_footer.html.erb
<div style="margin-top: 150px; float: left">

<!-- Footer -->
<footer class="page-footer font-small blue">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2018 Copyright:
    <a href="https://alpha-blog-prez.herokuapp.com//">Demo Alpha-Blog</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

</div>

app/views/layouts/_messages.html.erb
<div class="row">

  <div class="col-xs-10 col-xs-offset-1">

    <% flash.each do |name, msg| %>

        <div class='alert alert-<%="#{name}" %>'>

          <a href="#" class="close" data-dismiss="alert">×</a>

          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>

        </div>

    <% end %>

  </div>

</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Alpha-Blog', root_path, class:'navbar-brand', id: 'logo' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'View all articles', articles_path %></li>
        <li><%= link_to 'View all categories', categories_path %></li>
        <% if logged_in?  %>
        <li><%= link_to 'Create new article', new_article_url %></li>
      <% end %>
        <% if logged_in? && (current_user.admin) %>
            <li><%= link_to 'Create new category', new_category_url %></li>
      <% end %>

            </ul>
      <!--<form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>-->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'View all users', users_path %></li>
        <% if logged_in?  %>
            <li style="color: #BBBBBB; padding-top: 15px;"><%= current_user.email%></li>
        <% if current_user.admin?  %>
            <li style="color: #BBBBBB; padding-top: 15px;">(Admin)</li>
        <% end %>

              <li><%= link_to 'logout', logout_path, method: :delete  %> </li>

      <% else %>
            <li><%= link_to 'Sign up', signup_path %></li>
            <li><%= link_to 'login', login_path %></li>
      <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>

    <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<center><H1>This is the pages about page</H1>


<%= link_to 'Home', root_path %>

</center>

<br/>


<div style="float: left; width:400px; color:red">

  <p>Translated from the original Japanese version written by Yukihiro Matsumoto (the creator of Ruby),
    this version, by Goto Kentaro and Mark Slagell, is a nice overview of many aspects of the Ruby language.
  </p>
</div>


<div style="float: right; width:400px; color:blue">

  <p>An unconventional but interesting book that will teach you Ruby through stories, wit, and comics.
    Originally created by why the lucky stiff, this guide remains a classic for Ruby learners.</p></div>


<center><div>

  <p style="width:400px; color:green">The Koans walk you along the path to enlightenment in order to learn Ruby. The goal is
    to learn the Ruby language, syntax, structure, and some common functions and libraries. We also teach
    you culture.</p></div></center>

<hr/>

app/views/pages/home.html.erb
<div class="jumbotron">

  <center><H2>This is the Alpha-Blog home page</H2>
      <br/>
      <p><%= link_to "Sign Up", signup_path, class: "btn btn-success btn-lg" %></p>


    <br/>
      <h3 style="color: #2E2F30"><%= link_to 'About', pages_about_path %> | <%= link_to 'Article', articles_path %> </h3>

  </center>

</div>

app/views/users/_form.html.erb
<center>
  <%= render 'layouts/errors', obj:@users %>
  <div class="well">
    <%= form_for @users do  |f| %>
        <p>
          <%= f.label :username %><br/>
          <%= f.text_field :username, :class =>'form-control', :style =>'width: 50%;', :autofocus=>'true', :placeholder=>'Enter username' %>
        </p>
        <p>
          <%= f.label :email %><br/>
          <%= f.email_field :email, :class =>'form-control', :style =>'width: 50%;', :placeholder=>'Enter email' %>
        </p>
        <p>
          <%= f.label :password %><br/>
          <%= f.password_field :password, :class =>'form-control', :style =>'width: 50%;', :placeholder=>'Enter password' %>
        </p>
        <p>
          <%= f.submit(@users.new_record? ? "Sign up" : "Update account",:class => 'btn btn-primary') %>
        </p>
    <% end %>

    <br/>
    <%= link_to 'Articles', articles_path %>
  </div>
</center>

app/views/users/edit.html.erb
<center>
  <h1>Update your profile</h1>

  <%=	render 'form'  %>
</center>

app/views/users/index.html.erb
<center><h1>Listing all users</h1>
        <%= @users.count %>
      <center>
        <%=	 will_paginate @users %>
      </center>
    <% @users.each do |user| %>

        <div class="row">

          <div class="col-xs-8 col-xs-offset-2">

            <div class="well well-lg">

              <div class="article-title">
                <%=	link_to gravatar_for(user),user_path(user) %>
              </div>

              <div class="article-body">

                <%= truncate(user.username) %><hr/>
                <small>Email: <%= user.email %></small>
                <br/>
                <small><%=pluralize(user.articles.count, "article") if user.articles  %></small>
                <br/>
                <small>Created date: <%= time_ago_in_words(user.created_at) %> ago</small>
                <br/>
                <small>Updated date: <%= time_ago_in_words(user.updated_at) %> ago</small><br/>



              </div>


              <% if logged_in? && (current_user == user || current_user.admin?)  %>

                <div class="article-actions">

                  <%= link_to "Edit your profile", edit_user_path(user), class: "btn btn-xs btn-primary" %>

                  <%= link_to "Delete your profile", user_path(user), method: :delete,

                              data: { confirm: "Are you sure you want to delete this user?"},

                              class: "btn btn-xs btn-danger" %>

                </div>
               <%	end  %>

            </div>

          </div>

        </div>

    <% end %>
    <br/>
    <%= link_to 'Create new user', signup_url,:style =>'font-size:20px' %>
  <center>
    <%=	 will_paginate @users %>
  </center>
</center>

app/views/users/new.html.erb
<center>
<h1>Signup for Alpha Blog</h1>
<%= render 'layouts/errors', obj:@users %>
<div class="well">
  <%= form_for @users do  |f| %>
      <p>
        <%= f.label :username %><br/>
        <%= f.text_field :username, :class =>'form-control', :style =>'width: 50%;', :autofocus=>'true', :placeholder=>'Enter username' %>
      </p>
      <p>
        <%= f.label :email %><br/>
        <%= f.email_field :email, :class =>'form-control', :style =>'width: 50%;', :placeholder=>'Enter email' %>
      </p>
      <p>
        <%= f.label :password %><br/>
        <%= f.password_field :password, :class =>'form-control', :style =>'width: 50%;', :placeholder=>'Enter password' %>
      </p>
      <p>
        <%= f.submit "Signup",:class => 'btn btn-primary' %>
      </p>
  <% end %>

  <br/>
  <%= link_to 'Articles', articles_path %>
</div>
</center>

app/views/users/show.html.erb
<center>
  <h1>Welcome to <%= @users.username %>'s page</h1>
  <div class="row">
    <div >
      <%=	 gravatar_for @users, size: 150 %>

    </div>
  </div>
  <h4><%= @users.username %>'s articles</h4>
  <h4><%= @users.email %></h4>
  <h4>Articles <%= @users.articles.count %></h4>
  <br/>
  <center>
    <%=	 will_paginate @user_paginate %>
  </center>
</center>
  <%=	 render 'articles/articles', obj: @user_paginate  %>
</center>
<br/>
<center>
  <%=	 will_paginate @user_paginate %>
</center>
</center>

app/views/welcome/about.html.erb
<center><H1>This is the about us page</H1>

  <%= link_to 'Home', welcome_home_path  %>



</center>

app/views/welcome/home.html.erb
<center><H1>This is the home page</H1>


<%= link_to 'About', welcome_about_path  %>


</center>